version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.39
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustup component add rustfmt-preview
            rustfmt --version
            cargo fmt -- --check --color=auto
      - run:
          name: Check Linting
          command: |
            rustup component add clippy
            cargo clippy
      - run:
          name: Nightly Build
          command: |
            rustup toolchain install nightly
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Stable Build
          command: |
            rustup toolchain install stable
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
  coverage:
    machine: true
    steps:
      - checkout
      - run:
        name: Coverage with docker
        command: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin